kind: pipeline
name: default
type: docker

steps:
  - name: Perform Build
    image: ubuntu:20.04
    commands:
      - ./setup.sh
      - ./build.sh
      - ./deploy.sh
    environment:
      DEBIAN_FRONTEND: noninteractive
      ANDROID_HOME: /opt/android-sdk-linux
      ANDROID_NDK_HOME: /opt/android-ndk-r20b
      ANDROID_NDK_VERSION: r20
      PATH: /opt/android-ndk-r20b/android-ndk-r20b/prebuilt/linux-x86_64/bin:/opt/android-sdk-linux/cmake/3.10.2.4988404/bin:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/tools/bin:/opt/android-ndk-r20b/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NEXUS_PWD:
        from_secret: NEXUS_PWD

trigger:
  ref:
    - refs/heads/**
